### ISSUE TITLE
Create landing page 

### ISSUE THREAD

**Issue by NHL-Michel** [INF1-B/and-action#2]
Maken van de landing pagina (waar de abonnementen op staan)

**Comment by NHL-Michel** [comment]
To be updated: tekst over afbeelding, regisseurs abbonement, logo

**Comment by Mappeldorn** [comment]
![afbeelding](https://user-images.githubusercontent.com/37366890/144041253-9f26e9b6-8679-457b-bf94-d7a5113ae868.png)
