### ISSUE TITLE
Create login page

### ISSUE THREAD

**Issue by NHL-Michel** [INF1-B/and-action#3]

**Comment by NHL-Michel** [comment]
To be updated: logo

![image](https://user-images.githubusercontent.com/89914058/143849557-1fb74609-5bb5-49e9-8d5e-f48622d37965.png)

1.

**Comment by Mappeldorn** [comment]
![afbeelding](https://user-images.githubusercontent.com/37366890/144042043-28fb8942-e3c1-4386-b7d3-89a72355b7a4.png)
