### ISSUE TITLE
onderzoeken hoe de kwaliteit van een video beïnvloed kan worden (720p & 4k) - front-end of back-end

### ISSUE THREAD

**Issue by NHL-Michel** [INF1-B/and-action#33]

**Comment by Hajo300** [comment]
Download ffmpeg (windows):
https://www.youtube.com/watch?v=r1AtmY-RMyQ&t=44s
look in teams for a test on ffmpeg
Download ffmpeg (linux):
https://www.youtube.com/watch?v=tf4p-SMw5jA (not sure if this works for all of linux im not an expert)
