### ISSUE TITLE
Verzameling functies - authenticatie 

### ISSUE THREAD

**Issue by NHL-Michel** [INF1-B/and-action#37]
Maken van een verzameling functies dat ervoor zorgt dat een gebruiker

**Dit zou pas gedaan moeten worden zodra de front-end helemaal klaar is**

- In kan loggen en een sessie krijgt, hierbij moet er ook een update naar de database komen wat aangeeft dat de gebruiker is ingelogd (attribuut)
- Uit kan loggen, waarbij de sessie wordt kapot gemaakt en er een update naar de database komt wat aangeeft dat de gebruiker uitgelogd is (attribuut)
- een preloader komt bij alle .php die de sessie voor al het andere inlaad
- een gebruiker niet unauthenticated op een pagina kan komen

**Comment by MoraxUr** [comment]
Gaat 'm nie lukken lmao
